# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x0borg.example\"0\n\x12\x43\x61lculationRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"%\n\x13\x43\x61lculationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32[\n\x0f\x41\x64\x64itionService\x12H\n\x03\x41\x64\x64\x12\x1f.org.example.CalculationRequest\x1a .org.example.CalculationResponse2f\n\x15MultiplicationService\x12M\n\x08Multiply\x12\x1f.org.example.CalculationRequest\x1a .org.example.CalculationResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_CALCULATIONREQUEST']._serialized_start=33
  _globals['_CALCULATIONREQUEST']._serialized_end=81
  _globals['_CALCULATIONRESPONSE']._serialized_start=83
  _globals['_CALCULATIONRESPONSE']._serialized_end=120
  _globals['_ADDITIONSERVICE']._serialized_start=122
  _globals['_ADDITIONSERVICE']._serialized_end=213
  _globals['_MULTIPLICATIONSERVICE']._serialized_start=215
  _globals['_MULTIPLICATIONSERVICE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
